seed: 42
player_id: 1
n_actor_envs: 2
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObs
reward_space: GameResultReward
optimizer_class: Adam
model_arch: mha_model
embedding_dim: 128
hidden_dim: 256
n_heads: 4
n_blocks: 1
device: cpu
rescale_value_input: False
actor_device: cpu
learner_device: cpu
obs_space_kwargs: {}
reward_space_kwargs: {}