name: winning_position_reward
project: ConnectX
entity: filipinogambino
group: debug
use_mixed_precision: false
total_steps: 1000.0
batch_size: 8
checkpoint_freq: 60.0
num_actors: 2
n_actor_envs: 16
unroll_length: 16
player_id: 0
seed: 42
model_arch: mha_model
embedding_dim: 32
hidden_dim: 128
n_heads: 4
n_blocks: 1
device: cpu
rescale_value_input: false
obs_space_kwargs: {}
reward_space_kwargs: {}
debug: false
adversary: random
act_space: BasicActionSpace
obs_space: BasicObsSpace
reward_space: MoreInARowReward
optimizer_class: Adam
optimizer_kwargs:
  lr: 0.0001
  eps: 0.0003
min_lr_mod: 0.01
entropy_cost: 0.001
baseline_cost: 1.0
teacher_kl_cost: 0.0
lmb: 0.8
reduction: mean
actor_device: cpu
learner_device: cpu
disable_wandb: true
model_log_freq: 100
sharing_strategy: file_descriptor
num_buffers: 4
discounting: 0.999
clip_grads: 10.0
num_learner_threads: 1
use_teacher: false
teacher_baseline_cost: 0.0
use_index_select: true
load_dir: null
checkpoint_file: null
weights_only: false
n_value_warmup_batches: 0
