#defaults:
#- override hydra/job_logging: colorlog
#- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: new_beginnings
## WANDB params
# The wandb project name
project: ConnectX
# The wandb user to log to
entity: filipinogambino
# The wandb group for the run
group: debug

# Parameters to overwrite
use_mixed_precision: False
total_steps: 1e5
batch_size: 8
checkpoint_freq: 60.
num_actors: 2
n_actor_envs: 16
unroll_length: 16
player_id: 0
seed: 42
model_arch: vit_model
embedding_dim: 32
hidden_dim: 128
n_heads: 4
n_blocks: 1
device: cpu
rescale_value_input: False
obs_space_kwargs: {}
reward_space_kwargs: {}
normalize: False
debug: False

# Environment params
adversary: negamax

# Model params
act_space: BasicActionSpace
obs_space: BasicObsSpace
reward_space: MoreInARowReward

## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 1e-4
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.001
baseline_cost: 1.
teacher_kl_cost: 0.
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.8
reduction: mean

# MISCELLANEOUS params
actor_device: cpu
learner_device: cpu
disable_wandb: False
model_log_freq: 100
# file_descriptor or file_system
sharing_strategy: file_descriptor