#defaults:
#- override hydra/job_logging: colorlog
#- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

name: null
## WANDB params
# The wandb project name
project: ConnectX
# The wandb user to log to
entity: filipinogambino
# The wandb group for the run
group: debug

# Parameters to overwrite
total_steps: 1e4
batch_size: 8
checkpoint_freq: 60.
num_actors: 1
n_actor_envs: 2