wandb_version: 1

name:
  desc: null
  value: conv_historical_phase1
project:
  desc: null
  value: ConnectX
entity:
  desc: null
  value: filipinogambino
group:
  desc: null
  value: historical
use_mixed_precision:
  desc: null
  value: false
total_steps:
  desc: null
  value: 500000.0
batch_size:
  desc: null
  value: 8
checkpoint_freq:
  desc: null
  value: 60.0
num_actors:
  desc: null
  value: 1
n_actor_envs:
  desc: null
  value: 16
unroll_length:
  desc: null
  value: 16
seed:
  desc: null
  value: 42
model_arch:
  desc: null
  value: conv_model
embedding_dim:
  desc: null
  value: 32
hidden_dim:
  desc: null
  value: 128
kernel_size:
  desc: null
  value: 3
n_blocks:
  desc: null
  value: 8
device:
  desc: null
  value: cpu
rescale_value_input:
  desc: null
  value: false
rescale_se_input:
  desc: null
  value: false
obs_space_kwargs:
  desc: null
  value: {}
reward_space_kwargs:
  desc: null
  value: {}
normalize:
  desc: null
  value: false
debug:
  desc: null
  value: false
act_space:
  desc: null
  value: connectx.connectx_gym.act_spaces.BasicActionSpace
obs_space:
  desc: null
  value: connectx.connectx_gym.obs_spaces.HistoricalObs
reward_space:
  desc: null
  value: connectx.connectx_gym.reward_spaces.GameResultReward
optimizer_class:
  desc: null
  value: torch.optim.adam.Adam
optimizer_kwargs:
  desc: null
  value:
    lr: 5.0e-05
    eps: 0.0003
min_lr_mod:
  desc: null
  value: 0.01
entropy_cost:
  desc: null
  value: 0.001
baseline_cost:
  desc: null
  value: 1.0
teacher_kl_cost:
  desc: null
  value: 0.0
lmb:
  desc: null
  value: 0.8
reduction:
  desc: null
  value: mean
use_teacher:
  desc: null
  value: false
teacher_load_dir:
  desc: null
  value: none
teacher_checkpoint_file:
  desc: null
  value: none
actor_device:
  desc: null
  value: cpu
learner_device:
  desc: null
  value: cpu
disable_wandb:
  desc: null
  value: false
model_log_freq:
  desc: null
  value: 100
sharing_strategy:
  desc: null
  value: file_descriptor
num_buffers:
  desc: null
  value: 2
discounting:
  desc: null
  value: 0.999
clip_grads:
  desc: null
  value: 10.0
num_learner_threads:
  desc: null
  value: 1
teacher_baseline_cost:
  desc: null
  value: 0.0
load_dir:
  desc: null
  value: null
checkpoint_file:
  desc: null
  value: null
weights_only:
  desc: null
  value: false
n_value_warmup_batches:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1708543995.650553
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 55
      2:
      - 1
      - 11
      - 49
      - 50
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.9.6
      5: 0.16.3
      6: 4.35.0
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
