name: Workflow with secrets

on:
  workflow_dispatch:

jobs:
  run-monobeast:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Log-in to W&B
        shell: bash
        env:
          WANDB_API: ${{ secrets.WANDB_KEY }}
        run: wandb login "$WANDB_API"

      - name: Running monobeast
        run: python /home/runner/work/Connect_Four_2/run_monobeast.py