name: Running Monobeast

on:
  push:

jobs:
  run-monobeast:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip wheel https://files.pythonhosted.org/packages/87/6f/5284b5d1d82824db4cda3b46657968ae55053b2d33d5cd500ed60957777e/vec_noise-1.1.4-cp36-cp36m-win32.whl
        - run: pip install -r requirements.txt

#        - name: Install the packages
#          uses: BSFishy/pip-action@v1
#          with:
#            packages: wandb kaggle

        - name: Log-in to W&B
          shell: bash
          env:
            WANDB_API: ${{ secrets.WANDB_KEY }}
          run: wandb login "$WANDB_API"

        - name: Running monobeast
          run: python run_monobeast.py