name: Workflow with secrets

on:
  workflow_dispatch:

jobs:
  run-monobeast:
    runs-on: ubuntu-latest
    env:
      WANDB_KEY: ${{ secrets.WANDB_KEY }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.9'

      - name: Run monobeast
        run: python run_monobeast.py